name: Lint Code Base
description: The composite actions for megalinter
inputs:
  lints:
    required: false
    default: PYTHON,YAML,BASH
  excluded_regex:
    required: false
    default: '"*\.config\.py"|"ansible-playbooks/bucket\.*"'
  excluded_dirs: 
    required: false
    default: workflows

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
  - name: Megalinter
    uses: megalinter/megalinter/flavors/python@beta
    env:
      ENABLE: ${{inputs.lints}}
      FILTER_REGEX_EXCLUDE: ${{inputs.excluded_regex}}
      EXCLUDED_DIRECTORIES: ${{inputs.excluded_dirs}}
