name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to linter
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/linter
