name: Lint Code Base

on:
  workflow_call:
    inputs:
      lints:
        type: string
        default: PYTHON,YAML,BASH
      excluded_regex:
        type: string
        default: *\.config\.py'|'ansible-playbooks/bucket\.*
      excluded_dirs: 
        type: string
        default: workflows
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Megalinter
      uses: megalinter/megalinter/flavors/python@beta
      with:
        ENABLE: ${{inputs.lints}}
        FILTER_REGEX_EXCLUDE: '${{inputs.excluded_regex}}'
        EXCLUDED_DIRECTORIES: ${{inputs.excluded_dirs}}
